version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - "8000:8000"
  server:
    build: .
    image: gin-sample
    ports:
    - "8080:8080"
    volumes:
    - ./:/go/src/github.com/furiko/gin-sample